# Yext Answers CircleCI configuration
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.9
jobs:
  # generate bundles
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/answers
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - .circleci
  # run the jest unit tests
  unit_test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/answers
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
  # deploy to S3 in the root folder, overwriting the existing latest version
  deploy_latest:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/answers
    steps:
      - attach_workspace:
          at: ~/answers
      - run:
          name: Configure AWS
          command: |
            mkdir ~/.aws
            cp .circleci/aws_config ~/.aws/config
            echo -e $AWS_PROD_PROFILE >> ~/.aws/config
      - aws-s3/copy:
          from: dist
          to: '${AWS_DEPLOY_BUCKET}'
          arguments: |
            --acl public-read \
            --cache-control "no-cache" \
            --recursive \
            --profile production \
  # deploys assets to an uncached folder in the S3 bucket named by branch
  deploy_branch:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/answers
    steps:
      - attach_workspace:
          at: ~/answers
      - run:
          name: Configure AWS
          command: |
            mkdir ~/.aws
            cp .circleci/aws_config ~/.aws/config
            echo -e $AWS_PROD_PROFILE >> ~/.aws/config
      - aws-s3/copy:
          from: dist
          to: '${AWS_DEPLOY_BUCKET}/dev/${CIRCLE_BRANCH}'
          arguments: |
            --acl public-read \
            --cache-control "no-cache" \
            --recursive \
            --profile production \
  # deploys assets to a long-lived-cache folder in the S3 bucket named by release tag
  deploy_version:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/answers
    steps:
      - attach_workspace:
          at: ~/answers
      - run:
          name: Configure AWS
          command: |
            mkdir ~/.aws
            cp .circleci/aws_config ~/.aws/config
            echo -e $AWS_PROD_PROFILE >> ~/.aws/config
      - aws-s3/copy:
          from: dist
          to: '${AWS_DEPLOY_BUCKET}/${CIRCLE_TAG}'
          arguments: |
            --acl public-read \
            --cache-control "max-age=31536000" \
            --recursive \
            --profile production \
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - unit_test:
          filters:
            tags:
              only: /^v.*/
          requires:
            - build
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - unit_test
      - deploy_latest:
          filters:
            branches:
              only: master
          requires:
            - hold
      - deploy_branch:
          filters:
            branches:
              ignore: master
          requires:
            - unit_test
      - deploy_version:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - hold
