name: Run Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - name: Percy
      uses: percy/exec-action@v0.3.1
      with:
        command: npx percy exec -- npx testcafe "chrome:headless" tests/acceptance/percysnapshots.js
      env:
        PERCY_TOKEN: 1b2a74b07a76e9b532ebd2e68f63ddfd35d278f928fac791f25022f80cdfb160
